// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zkwhjldwlefxrtlsovgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inprd2hqbGR3bGVmeHJ0bHNvdmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzc2OTYsImV4cCI6MjA3MTcxMzY5Nn0.Jz6bg5p9x40Nwcwj8rcvwB7JQHu6vLzZhp1Xoocb13s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);